# Generated by Django 4.1.7 on 2023-05-15 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookShop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='author',
        ),
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
        migrations.AlterModelTable(
            name='city',
            table='city',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
        migrations.AlterModelTable(
            name='sale',
            table='sale',
        ),
    ]
